### ISSUE TITLE
Deploy before testing

### ISSUE THREAD

**Issue by Andersos** [netliferesearch/losen#110]
- [x] Get headsup from @elisejakob that we are ready
- [x] Release version of losen
- [x] Rename bundle to make sure web worker caching issue in cat fixed
- [x] Deploy cat with latest version of losen
- [x] Rename bundle to make sure web worker caching issue in ansvarsrett fixed
- [x] Deploy ansvarsrett with latest version of losen

**Comment by Andersos** [comment]
This is probably the issue we are seeing with caching on firebase https://github.com/facebookincubator/create-react-app/issues/2440

**Comment by kbrabrand** [comment]
👏
