### ISSUE TITLE
Result values displayed

### ISSUE THREAD

**Issue by Andersos** [netliferesearch/losen#99]
Figure out what to display on the result page for radio and checkboxes. Value "norwegian" mabye not correct
<img width="280" alt="screen shot 2017-10-10 at 17 11 57" src="https://user-images.githubusercontent.com/288977/31394239-293caf7a-adde-11e7-84fb-693e63ffcc58.png">

**Comment by kbrabrand** [comment]
Closed with 8cdecb48e6c8f64db8c8ca18787c8caba046503a

**Comment by Andersos** [comment]
Hmm, looks like the latest version still shows "norwegian", the value of the checkboxes and not the text "Et norsk firma". Any thoughts on why or how we can fix or change this?
<img width="280" alt="screen shot 2017-10-13 at 17 17 53" src="https://user-images.githubusercontent.com/288977/31553344-77173432-b03a-11e7-933d-32e8c2d0d93f.png">

**Comment by kbrabrand** [comment]
This is very strange. Was fixed earlier this week - I'll look into it. May be a regression

**Comment by kbrabrand** [comment]
The error here was that I was checking for an object (which is the case with the checkboxes), but in the case of a radio or select input the value is a scalar which I didn't catch. Now checks for all nodes with an `options` property, which covers Radio, Checkbox and Select.
